/** generated by scripts/split.js */

export default {
  "alpha2": "AI",
  "alpha3": "AIA",
  "country_code": "1",
  "country_name": "Anguilla",
  "mobile_begin_with": [
    "2645",
    "2647"
  ],
  "phone_number_lengths": [
    10
  ]
};