/** generated by scripts/split.js */

export default {
  "alpha2": "AS",
  "alpha3": "ASM",
  "country_code": "1",
  "country_name": "American Samoa",
  "mobile_begin_with": [
    "684733",
    "684258"
  ],
  "phone_number_lengths": [
    10
  ]
};