/** generated by scripts/split.js */

export default {
  "alpha2": "AG",
  "alpha3": "ATG",
  "country_code": "1",
  "country_name": "Antigua and Barbuda",
  "mobile_begin_with": [
    "2687"
  ],
  "phone_number_lengths": [
    10
  ]
};