/** generated by scripts/split.js */

export default {
  "alpha2": "BS",
  "alpha3": "BHS",
  "country_code": "1",
  "country_name": "Bahamas",
  "mobile_begin_with": [
    "242"
  ],
  "phone_number_lengths": [
    10
  ]
};