/** generated by scripts/split.js */

export default {
  "alpha2": "BM",
  "alpha3": "BMU",
  "country_code": "1",
  "country_name": "Bermuda",
  "mobile_begin_with": [
    "4413",
    "4415",
    "4417"
  ],
  "phone_number_lengths": [
    10
  ]
};