/** generated by scripts/split.js */

export default {
  "alpha2": "BB",
  "alpha3": "BRB",
  "country_code": "1",
  "country_name": "Barbados",
  "mobile_begin_with": [
    "246"
  ],
  "phone_number_lengths": [
    10
  ]
};