/** generated by scripts/split.js */

export default {
  "alpha2": "KY",
  "alpha3": "CYM",
  "country_code": "1",
  "country_name": "Cayman Islands",
  "mobile_begin_with": [
    "345"
  ],
  "phone_number_lengths": [
    10
  ]
};