/** generated by scripts/split.js */

export default {
  "alpha2": "DM",
  "alpha3": "DMA",
  "country_code": "1",
  "country_name": "Dominica",
  "mobile_begin_with": [
    "767"
  ],
  "phone_number_lengths": [
    10
  ]
};