/** generated by scripts/split.js */

export default {
  "alpha2": "DO",
  "alpha3": "DOM",
  "country_code": "1",
  "country_name": "Dominican Republic",
  "mobile_begin_with": [
    "809",
    "829",
    "849"
  ],
  "phone_number_lengths": [
    10
  ]
};