/** generated by scripts/split.js */

export default {
  "alpha2": "GD",
  "alpha3": "GRD",
  "country_code": "1",
  "country_name": "Grenada",
  "mobile_begin_with": [
    "473"
  ],
  "phone_number_lengths": [
    10
  ]
};