/** generated by scripts/split.js */

export default {
  "alpha2": "GU",
  "alpha3": "GUM",
  "country_code": "1",
  "country_name": "Guam",
  "mobile_begin_with": [
    "671"
  ],
  "phone_number_lengths": [
    10
  ]
};