/** generated by scripts/split.js */

export default {
  "alpha2": "JM",
  "alpha3": "JAM",
  "country_code": "1",
  "country_name": "Jamaica",
  "mobile_begin_with": [
    "876"
  ],
  "phone_number_lengths": [
    10
  ]
};