/** generated by scripts/split.js */

export default {
  "alpha2": "KN",
  "alpha3": "KNA",
  "country_code": "1",
  "country_name": "Saint Kitts And Nevis",
  "mobile_begin_with": [
    "869"
  ],
  "phone_number_lengths": [
    10
  ]
};