/** generated by scripts/split.js */

export default {
  "alpha2": "LC",
  "alpha3": "LCA",
  "country_code": "1",
  "country_name": "Saint Lucia",
  "mobile_begin_with": [
    "758"
  ],
  "phone_number_lengths": [
    10
  ]
};