/** generated by scripts/split.js */

export default {
  "alpha2": "MP",
  "alpha3": "MNP",
  "country_code": "1",
  "country_name": "Northern Mariana Islands",
  "mobile_begin_with": [
    "670"
  ],
  "phone_number_lengths": [
    10
  ]
};