/** generated by scripts/split.js */

export default {
  "alpha2": "MS",
  "alpha3": "MSR",
  "country_code": "1",
  "country_name": "Montserrat",
  "mobile_begin_with": [
    "664"
  ],
  "phone_number_lengths": [
    10
  ]
};