/** generated by scripts/split.js */

export default {
  "alpha2": "PR",
  "alpha3": "PRI",
  "country_code": "1",
  "country_name": "Puerto Rico",
  "mobile_begin_with": [
    "787",
    "939"
  ],
  "phone_number_lengths": [
    10
  ]
};