/** generated by scripts/split.js */

export default {
  "alpha2": "SX",
  "alpha3": "SXM",
  "country_code": "1",
  "country_name": "Sint Maarten",
  "mobile_begin_with": [
    "721"
  ],
  "phone_number_lengths": [
    10
  ]
};