/** generated by scripts/split.js */

export default {
  "alpha2": "TC",
  "alpha3": "TCA",
  "country_code": "1",
  "country_name": "Turks and Caicos Islands",
  "mobile_begin_with": [
    "6492",
    "6493",
    "6494"
  ],
  "phone_number_lengths": [
    10
  ]
};