/** generated by scripts/split.js */

export default {
  "alpha2": "TT",
  "alpha3": "TTO",
  "country_code": "1",
  "country_name": "Trinidad and Tobago",
  "mobile_begin_with": [
    "868"
  ],
  "phone_number_lengths": [
    10
  ]
};