/** generated by scripts/split.js */

export default {
  "alpha2": "VC",
  "alpha3": "VCT",
  "country_code": "1",
  "country_name": "Saint Vincent And The Grenedines",
  "mobile_begin_with": [
    "784"
  ],
  "phone_number_lengths": [
    10
  ]
};