/** generated by scripts/split.js */

export default {
  "alpha2": "VG",
  "alpha3": "VGB",
  "country_code": "1",
  "country_name": "Virgin Islands, British",
  "mobile_begin_with": [
    "284"
  ],
  "phone_number_lengths": [
    10
  ]
};