/** generated by scripts/split.js */

export default {
  "alpha2": "VI",
  "alpha3": "VIR",
  "country_code": "1",
  "country_name": "Virgin Islands, U.S.",
  "mobile_begin_with": [
    "340"
  ],
  "phone_number_lengths": [
    10
  ]
};