/** generated by scripts/split.js */

export default {
  "alpha2": "EG",
  "alpha3": "EGY",
  "country_code": "20",
  "country_name": "Egypt",
  "mobile_begin_with": [
    "1"
  ],
  "phone_number_lengths": [
    10,
    8
  ]
};