/** generated by scripts/split.js */

export default {
  "alpha2": "SS",
  "alpha3": "SSD",
  "country_code": "211",
  "country_name": "South Sudan",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};