/** generated by scripts/split.js */

export default {
  "alpha2": "MA",
  "alpha3": "MAR",
  "country_code": "212",
  "country_name": "Morocco",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};