/** generated by scripts/split.js */

export default {
  "alpha2": "DZ",
  "alpha3": "DZA",
  "country_code": "213",
  "country_name": "Algeria",
  "mobile_begin_with": [
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};