/** generated by scripts/split.js */

export default {
  "alpha2": "TN",
  "alpha3": "TUN",
  "country_code": "216",
  "country_name": "Tunisia",
  "mobile_begin_with": [
    "2",
    "4",
    "5",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};