/** generated by scripts/split.js */

export default {
  "alpha2": "LY",
  "alpha3": "LBY",
  "country_code": "218",
  "country_name": "Libyan Arab Jamahiriya",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};