/** generated by scripts/split.js */

export default {
  "alpha2": "GM",
  "alpha3": "GMB",
  "country_code": "220",
  "country_name": "Gambia",
  "mobile_begin_with": [
    "7",
    "9"
  ],
  "phone_number_lengths": [
    7
  ]
};