/** generated by scripts/split.js */

export default {
  "alpha2": "SN",
  "alpha3": "SEN",
  "country_code": "221",
  "country_name": "Senegal",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};