/** generated by scripts/split.js */

export default {
  "alpha2": "MR",
  "alpha3": "MRT",
  "country_code": "222",
  "country_name": "Mauritania",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    8
  ]
};