/** generated by scripts/split.js */

export default {
  "alpha2": "ML",
  "alpha3": "MLI",
  "country_code": "223",
  "country_name": "Mali",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};