/** generated by scripts/split.js */

export default {
  "alpha2": "GN",
  "alpha3": "GIN",
  "country_code": "224",
  "country_name": "Guinea",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    9
  ]
};