/** generated by scripts/split.js */

export default {
  "alpha2": "CI",
  "alpha3": "CIV",
  "country_code": "225",
  "country_name": "Côte D'Ivoire",
  "mobile_begin_with": [
    "0",
    "4",
    "5",
    "6",
    "7",
    "8"
  ],
  "phone_number_lengths": [
    8
  ]
};