/** generated by scripts/split.js */

export default {
  "alpha2": "BF",
  "alpha3": "BFA",
  "country_code": "226",
  "country_name": "Burkina Faso",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};