/** generated by scripts/split.js */

export default {
  "alpha2": "NE",
  "alpha3": "NER",
  "country_code": "227",
  "country_name": "Niger",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};