/** generated by scripts/split.js */

export default {
  "alpha2": "TG",
  "alpha3": "TGO",
  "country_code": "228",
  "country_name": "Togo",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};