/** generated by scripts/split.js */

export default {
  "alpha2": "BJ",
  "alpha3": "BEN",
  "country_code": "229",
  "country_name": "Benin",
  "mobile_begin_with": [
    "4",
    "6",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};