/** generated by scripts/split.js */

export default {
  "alpha2": "MU",
  "alpha3": "MUS",
  "country_code": "230",
  "country_name": "Mauritius",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    8
  ]
};