/** generated by scripts/split.js */

export default {
  "alpha2": "LR",
  "alpha3": "LBR",
  "country_code": "231",
  "country_name": "Liberia",
  "mobile_begin_with": [
    "4",
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    7,
    8
  ]
};