/** generated by scripts/split.js */

export default {
  "alpha2": "SL",
  "alpha3": "SLE",
  "country_code": "232",
  "country_name": "Sierra Leone",
  "mobile_begin_with": [
    "21",
    "25",
    "30",
    "33",
    "34",
    "40",
    "44",
    "50",
    "55",
    "76",
    "77",
    "78",
    "79",
    "88"
  ],
  "phone_number_lengths": [
    8
  ]
};