/** generated by scripts/split.js */

export default {
  "alpha2": "GH",
  "alpha3": "GHA",
  "country_code": "233",
  "country_name": "Ghana",
  "mobile_begin_with": [
    "2",
    "5"
  ],
  "phone_number_lengths": [
    9
  ]
};