/** generated by scripts/split.js */

export default {
  "alpha2": "NG",
  "alpha3": "NGA",
  "country_code": "234",
  "country_name": "Nigeria",
  "mobile_begin_with": [
    "70",
    "80",
    "81",
    "90"
  ],
  "phone_number_lengths": [
    10
  ]
};