/** generated by scripts/split.js */

export default {
  "alpha2": "TD",
  "alpha3": "TCD",
  "country_code": "235",
  "country_name": "Chad",
  "mobile_begin_with": [
    "6",
    "7",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};