/** generated by scripts/split.js */

export default {
  "alpha2": "CF",
  "alpha3": "CAF",
  "country_code": "236",
  "country_name": "Central African Republic",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};