/** generated by scripts/split.js */

export default {
  "alpha2": "CM",
  "alpha3": "CMR",
  "country_code": "237",
  "country_name": "Cameroon",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    9
  ]
};