/** generated by scripts/split.js */

export default {
  "alpha2": "CV",
  "alpha3": "CPV",
  "country_code": "238",
  "country_name": "Cape Verde",
  "mobile_begin_with": [
    "5",
    "9"
  ],
  "phone_number_lengths": [
    7
  ]
};