/** generated by scripts/split.js */

export default {
  "alpha2": "ST",
  "alpha3": "STP",
  "country_code": "239",
  "country_name": "Sao Tome and Principe",
  "mobile_begin_with": [
    "98",
    "99"
  ],
  "phone_number_lengths": [
    7
  ]
};