/** generated by scripts/split.js */

export default {
  "alpha2": "GQ",
  "alpha3": "GNQ",
  "country_code": "240",
  "country_name": "Equatorial Guinea",
  "mobile_begin_with": [
    "222",
    "551"
  ],
  "phone_number_lengths": [
    9
  ]
};