/** generated by scripts/split.js */

export default {
  "alpha2": "GA",
  "alpha3": "GAB",
  "country_code": "241",
  "country_name": "Gabon",
  "mobile_begin_with": [
    "2",
    "3",
    "4",
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    7
  ]
};