/** generated by scripts/split.js */

export default {
  "alpha2": "CG",
  "alpha3": "COG",
  "country_code": "242",
  "country_name": "Congo",
  "mobile_begin_with": [
    "0"
  ],
  "phone_number_lengths": [
    9
  ]
};