/** generated by scripts/split.js */

export default {
  "alpha2": "CD",
  "alpha3": "COD",
  "country_code": "243",
  "country_name": "Congo, The Democratic Republic Of The",
  "mobile_begin_with": [
    "8",
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};