/** generated by scripts/split.js */

export default {
  "alpha2": "AO",
  "alpha3": "AGO",
  "country_code": "244",
  "country_name": "Angola",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};