/** generated by scripts/split.js */

export default {
  "alpha2": "GW",
  "alpha3": "GNB",
  "country_code": "245",
  "country_name": "Guinea-Bissau",
  "mobile_begin_with": [
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    7
  ]
};