/** generated by scripts/split.js */

export default {
  "alpha2": "SC",
  "alpha3": "SYC",
  "country_code": "248",
  "country_name": "Seychelles",
  "mobile_begin_with": [
    "2"
  ],
  "phone_number_lengths": [
    7
  ]
};