/** generated by scripts/split.js */

export default {
  "alpha2": "SD",
  "alpha3": "SDN",
  "country_code": "249",
  "country_name": "Sudan",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};