/** generated by scripts/split.js */

export default {
  "alpha2": "RW",
  "alpha3": "RWA",
  "country_code": "250",
  "country_name": "Rwanda",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};