/** generated by scripts/split.js */

export default {
  "alpha2": "ET",
  "alpha3": "ETH",
  "country_code": "251",
  "country_name": "Ethiopia",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};