/** generated by scripts/split.js */

export default {
  "alpha2": "SO",
  "alpha3": "SOM",
  "country_code": "252",
  "country_name": "Somalia",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};