/** generated by scripts/split.js */

export default {
  "alpha2": "DJ",
  "alpha3": "DJI",
  "country_code": "253",
  "country_name": "Djibouti",
  "mobile_begin_with": [
    "77"
  ],
  "phone_number_lengths": [
    8
  ]
};