/** generated by scripts/split.js */

export default {
  "alpha2": "KE",
  "alpha3": "KEN",
  "country_code": "254",
  "country_name": "Kenya",
  "mobile_begin_with": [
    "7",
    "1"
  ],
  "phone_number_lengths": [
    9
  ]
};