/** generated by scripts/split.js */

export default {
  "alpha2": "TZ",
  "alpha3": "TZA",
  "country_code": "255",
  "country_name": "Tanzania, United Republic of",
  "mobile_begin_with": [
    "7",
    "6"
  ],
  "phone_number_lengths": [
    9
  ]
};