/** generated by scripts/split.js */

export default {
  "alpha2": "UG",
  "alpha3": "UGA",
  "country_code": "256",
  "country_name": "Uganda",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};