/** generated by scripts/split.js */

export default {
  "alpha2": "BI",
  "alpha3": "BDI",
  "country_code": "257",
  "country_name": "Burundi",
  "mobile_begin_with": [
    "7",
    "29"
  ],
  "phone_number_lengths": [
    8
  ]
};