/** generated by scripts/split.js */

export default {
  "alpha2": "MZ",
  "alpha3": "MOZ",
  "country_code": "258",
  "country_name": "Mozambique",
  "mobile_begin_with": [
    "8"
  ],
  "phone_number_lengths": [
    9
  ]
};