/** generated by scripts/split.js */

export default {
  "alpha2": "ZM",
  "alpha3": "ZMB",
  "country_code": "260",
  "country_name": "Zambia",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};