/** generated by scripts/split.js */

export default {
  "alpha2": "MG",
  "alpha3": "MDG",
  "country_code": "261",
  "country_name": "Madagascar",
  "mobile_begin_with": [
    "3"
  ],
  "phone_number_lengths": [
    9
  ]
};