/** generated by scripts/split.js */

export default {
  "alpha2": "YT",
  "alpha3": "MYT",
  "country_code": "262",
  "country_name": "Mayotte",
  "mobile_begin_with": [
    "639"
  ],
  "phone_number_lengths": [
    9
  ]
};