/** generated by scripts/split.js */

export default {
  "alpha2": "RE",
  "alpha3": "REU",
  "country_code": "262",
  "country_name": "Réunion",
  "mobile_begin_with": [
    "692",
    "693"
  ],
  "phone_number_lengths": [
    9
  ]
};