/** generated by scripts/split.js */

export default {
  "alpha2": "ZW",
  "alpha3": "ZWE",
  "country_code": "263",
  "country_name": "Zimbabwe",
  "mobile_begin_with": [
    "71",
    "73",
    "77"
  ],
  "phone_number_lengths": [
    9
  ]
};