/** generated by scripts/split.js */

export default {
  "alpha2": "NA",
  "alpha3": "NAM",
  "country_code": "264",
  "country_name": "Namibia",
  "mobile_begin_with": [
    "60",
    "81",
    "82",
    "85"
  ],
  "phone_number_lengths": [
    9
  ]
};