/** generated by scripts/split.js */

export default {
  "alpha2": "MW",
  "alpha3": "MWI",
  "country_code": "265",
  "country_name": "Malawi",
  "mobile_begin_with": [
    "77",
    "88",
    "99"
  ],
  "phone_number_lengths": [
    9
  ]
};