/** generated by scripts/split.js */

export default {
  "alpha2": "LS",
  "alpha3": "LSO",
  "country_code": "266",
  "country_name": "Lesotho",
  "mobile_begin_with": [
    "5",
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};