/** generated by scripts/split.js */

export default {
  "alpha2": "BW",
  "alpha3": "BWA",
  "country_code": "267",
  "country_name": "Botswana",
  "mobile_begin_with": [
    "71",
    "72",
    "73",
    "74",
    "75",
    "76"
  ],
  "phone_number_lengths": [
    8
  ]
};