/** generated by scripts/split.js */

export default {
  "alpha2": "KM",
  "alpha3": "COM",
  "country_code": "269",
  "country_name": "Comoros",
  "mobile_begin_with": [
    "3",
    "76"
  ],
  "phone_number_lengths": [
    7
  ]
};