/** generated by scripts/split.js */

export default {
  "alpha2": "ZA",
  "alpha3": "ZAF",
  "country_code": "27",
  "country_name": "South Africa",
  "mobile_begin_with": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8"
  ],
  "phone_number_lengths": [
    9
  ]
};