/** generated by scripts/split.js */

export default {
  "alpha2": "SH",
  "alpha3": "SHN",
  "country_code": "290",
  "country_name": "Saint Helena",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    4
  ]
};