/** generated by scripts/split.js */

export default {
  "alpha2": "ER",
  "alpha3": "ERI",
  "country_code": "291",
  "country_name": "Eritrea",
  "mobile_begin_with": [
    "1",
    "7",
    "8"
  ],
  "phone_number_lengths": [
    7
  ]
};