/** generated by scripts/split.js */

export default {
  "alpha2": "AW",
  "alpha3": "ABW",
  "country_code": "297",
  "country_name": "Aruba",
  "mobile_begin_with": [
    "5",
    "6",
    "7",
    "9"
  ],
  "phone_number_lengths": [
    7
  ]
};