/** generated by scripts/split.js */

export default {
  "alpha2": "FO",
  "alpha3": "FRO",
  "country_code": "298",
  "country_name": "Faroe Islands",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    6
  ]
};