/** generated by scripts/split.js */

export default {
  "alpha2": "GL",
  "alpha3": "GRL",
  "country_code": "299",
  "country_name": "Greenland",
  "mobile_begin_with": [
    "2",
    "4",
    "5"
  ],
  "phone_number_lengths": [
    6
  ]
};