/** generated by scripts/split.js */

export default {
  "alpha2": "GR",
  "alpha3": "GRC",
  "country_code": "30",
  "country_name": "Greece",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    10
  ]
};