/** generated by scripts/split.js */

export default {
  "alpha2": "NL",
  "alpha3": "NLD",
  "country_code": "31",
  "country_name": "Netherlands",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    9
  ]
};