/** generated by scripts/split.js */

export default {
  "alpha2": "BE",
  "alpha3": "BEL",
  "country_code": "32",
  "country_name": "Belgium",
  "mobile_begin_with": [
    "4",
    "3"
  ],
  "phone_number_lengths": [
    9,
    8
  ]
};