/** generated by scripts/split.js */

export default {
  "alpha2": "FR",
  "alpha3": "FRA",
  "country_code": "33",
  "country_name": "France",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};