/** generated by scripts/split.js */

export default {
  "alpha2": "ES",
  "alpha3": "ESP",
  "country_code": "34",
  "country_name": "Spain",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};