/** generated by scripts/split.js */

export default {
  "alpha2": "GI",
  "alpha3": "GIB",
  "country_code": "350",
  "country_name": "Gibraltar",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    8
  ]
};