/** generated by scripts/split.js */

export default {
  "alpha2": "PT",
  "alpha3": "PRT",
  "country_code": "351",
  "country_name": "Portugal",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};