/** generated by scripts/split.js */

export default {
  "alpha2": "LU",
  "alpha3": "LUX",
  "country_code": "352",
  "country_name": "Luxembourg",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    9
  ]
};