/** generated by scripts/split.js */

export default {
  "alpha2": "IE",
  "alpha3": "IRL",
  "country_code": "353",
  "country_name": "Ireland",
  "mobile_begin_with": [
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89"
  ],
  "phone_number_lengths": [
    9
  ]
};