/** generated by scripts/split.js */

export default {
  "alpha2": "IS",
  "alpha3": "ISL",
  "country_code": "354",
  "country_name": "Iceland",
  "mobile_begin_with": [
    "6",
    "7",
    "8"
  ],
  "phone_number_lengths": [
    7
  ]
};