/** generated by scripts/split.js */

export default {
  "alpha2": "AL",
  "alpha3": "ALB",
  "country_code": "355",
  "country_name": "Albania",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    9
  ]
};