/** generated by scripts/split.js */

export default {
  "alpha2": "MT",
  "alpha3": "MLT",
  "country_code": "356",
  "country_name": "Malta",
  "mobile_begin_with": [
    "7",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};