/** generated by scripts/split.js */

export default {
  "alpha2": "CY",
  "alpha3": "CYP",
  "country_code": "357",
  "country_name": "Cyprus",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};