/** generated by scripts/split.js */

export default {
  "alpha2": "FI",
  "alpha3": "FIN",
  "country_code": "358",
  "country_name": "Finland",
  "mobile_begin_with": [
    "4",
    "5"
  ],
  "phone_number_lengths": [
    9,
    10
  ]
};