/** generated by scripts/split.js */

export default {
  "alpha2": "AX",
  "alpha3": "ALA",
  "country_code": "358",
  "country_name": "Åland Islands",
  "mobile_begin_with": [
    "18"
  ],
  "phone_number_lengths": [
    6,
    7,
    8
  ]
};