/** generated by scripts/split.js */

export default {
  "alpha2": "BG",
  "alpha3": "BGR",
  "country_code": "359",
  "country_name": "Bulgaria",
  "mobile_begin_with": [
    "87",
    "88",
    "89",
    "98",
    "99",
    "43"
  ],
  "phone_number_lengths": [
    8,
    9
  ]
};