/** generated by scripts/split.js */

export default {
  "alpha2": "HU",
  "alpha3": "HUN",
  "country_code": "36",
  "country_name": "Hungary",
  "mobile_begin_with": [
    "20",
    "30",
    "31",
    "70"
  ],
  "phone_number_lengths": [
    9
  ]
};