/** generated by scripts/split.js */

export default {
  "alpha2": "LT",
  "alpha3": "LTU",
  "country_code": "370",
  "country_name": "Lithuania",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};