/** generated by scripts/split.js */

export default {
  "alpha2": "LV",
  "alpha3": "LVA",
  "country_code": "371",
  "country_name": "Latvia",
  "mobile_begin_with": [
    "2"
  ],
  "phone_number_lengths": [
    8
  ]
};