/** generated by scripts/split.js */

export default {
  "alpha2": "EE",
  "alpha3": "EST",
  "country_code": "372",
  "country_name": "Estonia",
  "mobile_begin_with": [
    "5",
    "81",
    "82",
    "83"
  ],
  "phone_number_lengths": [
    7,
    8
  ]
};