/** generated by scripts/split.js */

export default {
  "alpha2": "MD",
  "alpha3": "MDA",
  "country_code": "373",
  "country_name": "Moldova, Republic of",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};