/** generated by scripts/split.js */

export default {
  "alpha2": "AM",
  "alpha3": "ARM",
  "country_code": "374",
  "country_name": "Armenia",
  "mobile_begin_with": [
    "4",
    "5",
    "7",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};