/** generated by scripts/split.js */

export default {
  "alpha2": "BY",
  "alpha3": "BLR",
  "country_code": "375",
  "country_name": "Belarus",
  "mobile_begin_with": [
    "25",
    "29",
    "33",
    "44"
  ],
  "phone_number_lengths": [
    9
  ]
};