/** generated by scripts/split.js */

export default {
  "alpha2": "AD",
  "alpha3": "AND",
  "country_code": "376",
  "country_name": "Andorra",
  "mobile_begin_with": [
    "3",
    "4",
    "6"
  ],
  "phone_number_lengths": [
    6
  ]
};