/** generated by scripts/split.js */

export default {
  "alpha2": "MC",
  "alpha3": "MCO",
  "country_code": "377",
  "country_name": "Monaco",
  "mobile_begin_with": [
    "4",
    "6"
  ],
  "phone_number_lengths": [
    8,
    9
  ]
};