/** generated by scripts/split.js */

export default {
  "alpha2": "SM",
  "alpha3": "SMR",
  "country_code": "378",
  "country_name": "San Marino",
  "mobile_begin_with": [
    "3",
    "6"
  ],
  "phone_number_lengths": [
    10
  ]
};