/** generated by scripts/split.js */

export default {
  "alpha2": "UA",
  "alpha3": "UKR",
  "country_code": "380",
  "country_name": "Ukraine",
  "mobile_begin_with": [
    "39",
    "50",
    "63",
    "66",
    "67",
    "68",
    "73",
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};