/** generated by scripts/split.js */

export default {
  "alpha2": "RS",
  "alpha3": "SRB",
  "country_code": "381",
  "country_name": "Serbia",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8,
    9
  ]
};