/** generated by scripts/split.js */

export default {
  "alpha2": "ME",
  "alpha3": "MNE",
  "country_code": "382",
  "country_name": "Montenegro",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};