/** generated by scripts/split.js */

export default {
  "alpha2": "HR",
  "alpha3": "HRV",
  "country_code": "385",
  "country_name": "Croatia",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8,
    9
  ]
};