/** generated by scripts/split.js */

export default {
  "alpha2": "SI",
  "alpha3": "SVN",
  "country_code": "386",
  "country_name": "Slovenia",
  "mobile_begin_with": [
    "3",
    "4",
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};