/** generated by scripts/split.js */

export default {
  "alpha2": "BA",
  "alpha3": "BIH",
  "country_code": "387",
  "country_name": "Bosnia and Herzegovina",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};