/** generated by scripts/split.js */

export default {
  "alpha2": "MK",
  "alpha3": "MKD",
  "country_code": "389",
  "country_name": "Macedonia, the Former Yugoslav Republic Of",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};