/** generated by scripts/split.js */

export default {
  "alpha2": "IT",
  "alpha3": "ITA",
  "country_code": "39",
  "country_name": "Italy",
  "mobile_begin_with": [
    "3"
  ],
  "phone_number_lengths": [
    9,
    10
  ]
};