/** generated by scripts/split.js */

export default {
  "alpha2": "RO",
  "alpha3": "ROU",
  "country_code": "40",
  "country_name": "Romania",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};