/** generated by scripts/split.js */

export default {
  "alpha2": "CH",
  "alpha3": "CHE",
  "country_code": "41",
  "country_name": "Switzerland",
  "mobile_begin_with": [
    "74",
    "75",
    "76",
    "77",
    "78",
    "79"
  ],
  "phone_number_lengths": [
    9
  ]
};