/** generated by scripts/split.js */

export default {
  "alpha2": "CZ",
  "alpha3": "CZE",
  "country_code": "420",
  "country_name": "Czech Republic",
  "mobile_begin_with": [
    "6",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};