/** generated by scripts/split.js */

export default {
  "alpha2": "SK",
  "alpha3": "SVK",
  "country_code": "421",
  "country_name": "Slovakia",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};