/** generated by scripts/split.js */

export default {
  "alpha2": "LI",
  "alpha3": "LIE",
  "country_code": "423",
  "country_name": "Liechtenstein",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    7
  ]
};