/** generated by scripts/split.js */

export default {
  "alpha2": "AT",
  "alpha3": "AUT",
  "country_code": "43",
  "country_name": "Austria",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    10,
    11,
    12,
    13,
    14
  ]
};