/** generated by scripts/split.js */

export default {
  "alpha2": "GB",
  "alpha3": "GBR",
  "country_code": "44",
  "country_name": "United Kingdom",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    10
  ]
};