/** generated by scripts/split.js */

export default {
  "alpha2": "DK",
  "alpha3": "DNK",
  "country_code": "45",
  "country_name": "Denmark",
  "mobile_begin_with": [
    "2",
    "30",
    "31",
    "40",
    "41",
    "42",
    "50",
    "51",
    "52",
    "53",
    "60",
    "61",
    "71",
    "81",
    "91",
    "92",
    "93"
  ],
  "phone_number_lengths": [
    8
  ]
};