/** generated by scripts/split.js */

export default {
  "alpha2": "SE",
  "alpha3": "SWE",
  "country_code": "46",
  "country_name": "Sweden",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};