/** generated by scripts/split.js */

export default {
  "alpha2": "NO",
  "alpha3": "NOR",
  "country_code": "47",
  "country_name": "Norway",
  "mobile_begin_with": [
    "4",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};