/** generated by scripts/split.js */

export default {
  "alpha2": "SJ",
  "alpha3": "SJM",
  "country_code": "47",
  "country_name": "Svalbard And Jan Mayen",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    8
  ]
};