/** generated by scripts/split.js */

export default {
  "alpha2": "PL",
  "alpha3": "POL",
  "country_code": "48",
  "country_name": "Poland",
  "mobile_begin_with": [
    "4",
    "5",
    "6",
    "7",
    "8"
  ],
  "phone_number_lengths": [
    9
  ]
};