/** generated by scripts/split.js */

export default {
  "alpha2": "DE",
  "alpha3": "DEU",
  "country_code": "49",
  "country_name": "Germany",
  "mobile_begin_with": [
    "15",
    "16",
    "17"
  ],
  "phone_number_lengths": [
    10,
    11
  ]
};