/** generated by scripts/split.js */

export default {
  "alpha2": "FK",
  "alpha3": "FLK",
  "country_code": "500",
  "country_name": "Falkland Islands (Malvinas)",
  "mobile_begin_with": [
    "5",
    "6"
  ],
  "phone_number_lengths": [
    5
  ]
};