/** generated by scripts/split.js */

export default {
  "alpha2": "BZ",
  "alpha3": "BLZ",
  "country_code": "501",
  "country_name": "Belize",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    7
  ]
};