/** generated by scripts/split.js */

export default {
  "alpha2": "GT",
  "alpha3": "GTM",
  "country_code": "502",
  "country_name": "Guatemala",
  "mobile_begin_with": [
    "3",
    "4",
    "5"
  ],
  "phone_number_lengths": [
    8
  ]
};