/** generated by scripts/split.js */

export default {
  "alpha2": "SV",
  "alpha3": "SLV",
  "country_code": "503",
  "country_name": "El Salvador",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};