/** generated by scripts/split.js */

export default {
  "alpha2": "HN",
  "alpha3": "HND",
  "country_code": "504",
  "country_name": "Honduras",
  "mobile_begin_with": [
    "3",
    "7",
    "8",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};