/** generated by scripts/split.js */

export default {
  "alpha2": "NI",
  "alpha3": "NIC",
  "country_code": "505",
  "country_name": "Nicaragua",
  "mobile_begin_with": [
    "8"
  ],
  "phone_number_lengths": [
    8
  ]
};