/** generated by scripts/split.js */

export default {
  "alpha2": "PA",
  "alpha3": "PAN",
  "country_code": "507",
  "country_name": "Panama",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};