/** generated by scripts/split.js */

export default {
  "alpha2": "PM",
  "alpha3": "SPM",
  "country_code": "508",
  "country_name": "Saint Pierre And Miquelon",
  "mobile_begin_with": [
    "55"
  ],
  "phone_number_lengths": [
    6
  ]
};