/** generated by scripts/split.js */

export default {
  "alpha2": "HT",
  "alpha3": "HTI",
  "country_code": "509",
  "country_name": "Haiti",
  "mobile_begin_with": [
    "3",
    "4"
  ],
  "phone_number_lengths": [
    8
  ]
};