/** generated by scripts/split.js */

export default {
  "alpha2": "PE",
  "alpha3": "PER",
  "country_code": "51",
  "country_name": "Peru",
  "mobile_begin_with": [
    "9",
    "6"
  ],
  "phone_number_lengths": [
    9,
    8
  ]
};