/** generated by scripts/split.js */

export default {
  "alpha2": "MX",
  "alpha3": "MEX",
  "country_code": "52",
  "country_name": "Mexico",
  "mobile_begin_with": [
    ""
  ],
  "phone_number_lengths": [
    10,
    11
  ]
};