/** generated by scripts/split.js */

export default {
  "alpha2": "CU",
  "alpha3": "CUB",
  "country_code": "53",
  "country_name": "Cuba",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    8
  ]
};