/** generated by scripts/split.js */

export default {
  "alpha2": "AR",
  "alpha3": "ARG",
  "country_code": "54",
  "country_name": "Argentina",
  "mobile_begin_with": [
    "1",
    "2",
    "3"
  ],
  "phone_number_lengths": [
    10
  ]
};