/** generated by scripts/split.js */

export default {
  "alpha2": "CL",
  "alpha3": "CHL",
  "country_code": "56",
  "country_name": "Chile",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};