/** generated by scripts/split.js */

export default {
  "alpha2": "CO",
  "alpha3": "COL",
  "country_code": "57",
  "country_name": "Colombia",
  "mobile_begin_with": [
    "3"
  ],
  "phone_number_lengths": [
    10
  ]
};