/** generated by scripts/split.js */

export default {
  "alpha2": "VE",
  "alpha3": "VEN",
  "country_code": "58",
  "country_name": "Venezuela, Bolivarian Republic of",
  "mobile_begin_with": [
    "4"
  ],
  "phone_number_lengths": [
    10
  ]
};