/** generated by scripts/split.js */

export default {
  "alpha2": "GP",
  "alpha3": "GLP",
  "country_code": "590",
  "country_name": "Guadeloupe",
  "mobile_begin_with": [
    "690"
  ],
  "phone_number_lengths": [
    9
  ]
};