/** generated by scripts/split.js */

export default {
  "alpha2": "BO",
  "alpha3": "BOL",
  "country_code": "591",
  "country_name": "Bolivia",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};