/** generated by scripts/split.js */

export default {
  "alpha2": "GY",
  "alpha3": "GUY",
  "country_code": "592",
  "country_name": "Guyana",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    7
  ]
};