/** generated by scripts/split.js */

export default {
  "alpha2": "EC",
  "alpha3": "ECU",
  "country_code": "593",
  "country_name": "Ecuador",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};