/** generated by scripts/split.js */

export default {
  "alpha2": "GF",
  "alpha3": "GUF",
  "country_code": "594",
  "country_name": "French Guiana",
  "mobile_begin_with": [
    "694"
  ],
  "phone_number_lengths": [
    9
  ]
};