/** generated by scripts/split.js */

export default {
  "alpha2": "PY",
  "alpha3": "PRY",
  "country_code": "595",
  "country_name": "Paraguay",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};