/** generated by scripts/split.js */

export default {
  "alpha2": "MQ",
  "alpha3": "MTQ",
  "country_code": "596",
  "country_name": "Martinique",
  "mobile_begin_with": [
    "696"
  ],
  "phone_number_lengths": [
    9
  ]
};