/** generated by scripts/split.js */

export default {
  "alpha2": "SR",
  "alpha3": "SUR",
  "country_code": "597",
  "country_name": "Suriname",
  "mobile_begin_with": [
    "6",
    "7",
    "8"
  ],
  "phone_number_lengths": [
    7
  ]
};