/** generated by scripts/split.js */

export default {
  "alpha2": "UY",
  "alpha3": "URY",
  "country_code": "598",
  "country_name": "Uruguay",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};