/** generated by scripts/split.js */

export default {
  "alpha2": "MY",
  "alpha3": "MYS",
  "country_code": "60",
  "country_name": "Malaysia",
  "mobile_begin_with": [
    "1",
    "6"
  ],
  "phone_number_lengths": [
    9,
    10,
    8
  ]
};