/** generated by scripts/split.js */

export default {
  "alpha2": "AU",
  "alpha3": "AUS",
  "country_code": "61",
  "country_name": "Australia",
  "mobile_begin_with": [
    "4"
  ],
  "phone_number_lengths": [
    9
  ]
};