/** generated by scripts/split.js */

export default {
  "alpha2": "ID",
  "alpha3": "IDN",
  "country_code": "62",
  "country_name": "Indonesia",
  "mobile_begin_with": [
    "8"
  ],
  "phone_number_lengths": [
    9,
    10,
    11,
    12
  ]
};