/** generated by scripts/split.js */

export default {
  "alpha2": "PH",
  "alpha3": "PHL",
  "country_code": "63",
  "country_name": "Philippines",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    10
  ]
};