/** generated by scripts/split.js */

export default {
  "alpha2": "NZ",
  "alpha3": "NZL",
  "country_code": "64",
  "country_name": "New Zealand",
  "mobile_begin_with": [
    "2",
  ],
  "phone_number_lengths": [
    8,
    9,
    10
  ]
};