/** generated by scripts/split.js */

export default {
  "alpha2": "SG",
  "alpha3": "SGP",
  "country_code": "65",
  "country_name": "Singapore",
  "mobile_begin_with": [
    "8",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};