/** generated by scripts/split.js */

export default {
  "alpha2": "TH",
  "alpha3": "THA",
  "country_code": "66",
  "country_name": "Thailand",
  "mobile_begin_with": [
    "6",
    "8",
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};