/** generated by scripts/split.js */

export default {
  "alpha2": "TL",
  "alpha3": "TLS",
  "country_code": "670",
  "country_name": "Timor-Leste",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};