/** generated by scripts/split.js */

export default {
  "alpha2": "NF",
  "alpha3": "NFK",
  "country_code": "672",
  "country_name": "Norfolk Island",
  "mobile_begin_with": [
    "5",
    "8"
  ],
  "phone_number_lengths": [
    5
  ]
};