/** generated by scripts/split.js */

export default {
  "alpha2": "BN",
  "alpha3": "BRN",
  "country_code": "673",
  "country_name": "Brunei Darussalam",
  "mobile_begin_with": [
    "7",
    "8"
  ],
  "phone_number_lengths": [
    7
  ]
};