/** generated by scripts/split.js */

export default {
  "alpha2": "NR",
  "alpha3": "NRU",
  "country_code": "674",
  "country_name": "Nauru",
  "mobile_begin_with": [
    "555"
  ],
  "phone_number_lengths": [
    7
  ]
};