/** generated by scripts/split.js */

export default {
  "alpha2": "PG",
  "alpha3": "PNG",
  "country_code": "675",
  "country_name": "Papua New Guinea",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};