/** generated by scripts/split.js */

export default {
  "alpha2": "TO",
  "alpha3": "TON",
  "country_code": "676",
  "country_name": "Tonga",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    5
  ]
};