/** generated by scripts/split.js */

export default {
  "alpha2": "SB",
  "alpha3": "SLB",
  "country_code": "677",
  "country_name": "Solomon Islands",
  "mobile_begin_with": [
    "7",
    "8"
  ],
  "phone_number_lengths": [
    7
  ]
};