/** generated by scripts/split.js */

export default {
  "alpha2": "VU",
  "alpha3": "VUT",
  "country_code": "678",
  "country_name": "Vanuatu",
  "mobile_begin_with": [
    "5",
    "7"
  ],
  "phone_number_lengths": [
    7
  ]
};