/** generated by scripts/split.js */

export default {
  "alpha2": "FJ",
  "alpha3": "FJI",
  "country_code": "679",
  "country_name": "Fiji",
  "mobile_begin_with": [
    "7",
    "9"
  ],
  "phone_number_lengths": [
    7
  ]
};