/** generated by scripts/split.js */

export default {
  "alpha2": "PW",
  "alpha3": "PLW",
  "country_code": "680",
  "country_name": "Palau",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    7
  ]
};