/** generated by scripts/split.js */

export default {
  "alpha2": "WF",
  "alpha3": "WLF",
  "country_code": "681",
  "country_name": "Wallis and Futuna",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    6
  ]
};