/** generated by scripts/split.js */

export default {
  "alpha2": "CK",
  "alpha3": "COK",
  "country_code": "682",
  "country_name": "Cook Islands",
  "mobile_begin_with": [
    "5",
    "7"
  ],
  "phone_number_lengths": [
    5
  ]
};