/** generated by scripts/split.js */

export default {
  "alpha2": "NU",
  "alpha3": "NIU",
  "country_code": "683",
  "country_name": "Niue",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    4
  ]
};