/** generated by scripts/split.js */

export default {
  "alpha2": "WS",
  "alpha3": "WSM",
  "country_code": "685",
  "country_name": "Samoa",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    7
  ]
};