/** generated by scripts/split.js */

export default {
  "alpha2": "KI",
  "alpha3": "KIR",
  "country_code": "686",
  "country_name": "Kiribati",
  "mobile_begin_with": [
    "9",
    "30"
  ],
  "phone_number_lengths": [
    5
  ]
};