/** generated by scripts/split.js */

export default {
  "alpha2": "NC",
  "alpha3": "NCL",
  "country_code": "687",
  "country_name": "New Caledonia",
  "mobile_begin_with": [
    "7",
    "8",
    "9"
  ],
  "phone_number_lengths": [
    6
  ]
};