/** generated by scripts/split.js */

export default {
  "alpha2": "TV",
  "alpha3": "TUV",
  "country_code": "688",
  "country_name": "Tuvalu",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    5
  ]
};