/** generated by scripts/split.js */

export default {
  "alpha2": "PF",
  "alpha3": "PYF",
  "country_code": "689",
  "country_name": "French Polynesia",
  "mobile_begin_with": [
    "8"
  ],
  "phone_number_lengths": [
    8
  ]
};