/** generated by scripts/split.js */

export default {
  "alpha2": "TK",
  "alpha3": "TKL",
  "country_code": "690",
  "country_name": "Tokelau",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    4
  ]
};