/** generated by scripts/split.js */

export default {
  "alpha2": "FM",
  "alpha3": "FSM",
  "country_code": "691",
  "country_name": "Micronesia, Federated States Of",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    7
  ]
};