/** generated by scripts/split.js */

export default {
  "alpha2": "MH",
  "alpha3": "MHL",
  "country_code": "692",
  "country_name": "Marshall Islands",
  "mobile_begin_with": [],
  "phone_number_lengths": [
    7
  ]
};