/** generated by scripts/split.js */

export default {
  "alpha2": "KZ",
  "alpha3": "KAZ",
  "country_code": "7",
  "country_name": "Kazakhstan",
  "mobile_begin_with": [
    "70",
    "74",
    "77"
  ],
  "phone_number_lengths": [
    10
  ]
};