/** generated by scripts/split.js */

export default {
  "alpha2": "RU",
  "alpha3": "RUS",
  "country_code": "7",
  "country_name": "Russian Federation",
  "mobile_begin_with": [
    "9",
    "495"
  ],
  "phone_number_lengths": [
    10
  ]
};