/** generated by scripts/split.js */

export default {
  "alpha2": "JP",
  "alpha3": "JPN",
  "country_code": "81",
  "country_name": "Japan",
  "mobile_begin_with": [
    "70",
    "80",
    "90"
  ],
  "phone_number_lengths": [
    10
  ]
};