/** generated by scripts/split.js */

export default {
  "alpha2": "KR",
  "alpha3": "KOR",
  "country_code": "82",
  "country_name": "Korea, Republic of",
  "mobile_begin_with": [
    "1"
  ],
  "phone_number_lengths": [
    9,
    10
  ]
};