/** generated by scripts/split.js */

export default {
  "alpha2": "VN",
  "alpha3": "VNM",
  "country_code": "84",
  "country_name": "Viet Nam",
  "mobile_begin_with": [
    "8",
    "9",
    "3",
    "7",
    "5"
  ],
  "phone_number_lengths": [
    9
  ]
};