/** generated by scripts/split.js */

export default {
  "alpha2": "HK",
  "alpha3": "HKG",
  "country_code": "852",
  "country_name": "Hong Kong",
  "mobile_begin_with": [
    "4",
    "5",
    "6",
    "70",
    "71",
    "72",
    "73",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};