/** generated by scripts/split.js */

export default {
  "alpha2": "MO",
  "alpha3": "MAC",
  "country_code": "853",
  "country_name": "Macao",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};