/** generated by scripts/split.js */

export default {
  "alpha2": "KH",
  "alpha3": "KHM",
  "country_code": "855",
  "country_name": "Cambodia",
  "mobile_begin_with": [
    "1",
    "6",
    "7",
    "8",
    "9"
  ],
  "phone_number_lengths": [
    8,
    9
  ]
};