/** generated by scripts/split.js */

export default {
  "alpha2": "LA",
  "alpha3": "LAO",
  "country_code": "856",
  "country_name": "Lao People's Democratic Republic",
  "mobile_begin_with": [
    "20"
  ],
  "phone_number_lengths": [
    10
  ]
};