/** generated by scripts/split.js */

export default {
  "alpha2": "CN",
  "alpha3": "CHN",
  "country_code": "86",
  "country_name": "China",
  "mobile_begin_with": [
    "13",
    "14",
    "15",
    "17",
    "18",
    "19",
    "16"
  ],
  "phone_number_lengths": [
    11
  ]
};