/** generated by scripts/split.js */

export default {
  "alpha2": "BD",
  "alpha3": "BGD",
  "country_code": "880",
  "country_name": "Bangladesh",
  "mobile_begin_with": [
    "1"
  ],
  "phone_number_lengths": [
    8,
    9,
    10
  ]
};