/** generated by scripts/split.js */

export default {
  "alpha2": "TW",
  "alpha3": "TWN",
  "country_code": "886",
  "country_name": "Taiwan",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};