/** generated by scripts/split.js */

export default {
  "alpha2": "TR",
  "alpha3": "TUR",
  "country_code": "90",
  "country_name": "Turkey",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    10
  ]
};