/** generated by scripts/split.js */

export default {
  "alpha2": "IN",
  "alpha3": "IND",
  "country_code": "91",
  "country_name": "India",
  "mobile_begin_with": [
    "6",
    "7",
    "8",
    "9"
  ],
  "phone_number_lengths": [
    10
  ]
};