/** generated by scripts/split.js */

export default {
  "alpha2": "PK",
  "alpha3": "PAK",
  "country_code": "92",
  "country_name": "Pakistan",
  "mobile_begin_with": [
    "3"
  ],
  "phone_number_lengths": [
    10
  ]
};