/** generated by scripts/split.js */

export default {
  "alpha2": "AF",
  "alpha3": "AFG",
  "country_code": "93",
  "country_name": "Afghanistan",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};