/** generated by scripts/split.js */

export default {
  "alpha2": "LK",
  "alpha3": "LKA",
  "country_code": "94",
  "country_name": "Sri Lanka",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};