/** generated by scripts/split.js */

export default {
  "alpha2": "MM",
  "alpha3": "MMR",
  "country_code": "95",
  "country_name": "Myanmar",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8,
    9,
    10
  ]
};