/** generated by scripts/split.js */

export default {
  "alpha2": "MV",
  "alpha3": "MDV",
  "country_code": "960",
  "country_name": "Maldives",
  "mobile_begin_with": [
    "7",
    "9"
  ],
  "phone_number_lengths": [
    7
  ]
};