/** generated by scripts/split.js */

export default {
  "alpha2": "LB",
  "alpha3": "LBN",
  "country_code": "961",
  "country_name": "Lebanon",
  "mobile_begin_with": [
    "3",
    "7"
  ],
  "phone_number_lengths": [
    7,
    8
  ]
};