/** generated by scripts/split.js */

export default {
  "alpha2": "JO",
  "alpha3": "JOR",
  "country_code": "962",
  "country_name": "Jordan",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};