/** generated by scripts/split.js */

export default {
  "alpha2": "SY",
  "alpha3": "SYR",
  "country_code": "963",
  "country_name": "Syrian Arab Republic",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};