/** generated by scripts/split.js */

export default {
  "alpha2": "IQ",
  "alpha3": "IRQ",
  "country_code": "964",
  "country_name": "Iraq",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    10
  ]
};