/** generated by scripts/split.js */

export default {
  "alpha2": "KW",
  "alpha3": "KWT",
  "country_code": "965",
  "country_name": "Kuwait",
  "mobile_begin_with": [
    "5",
    "6",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};