/** generated by scripts/split.js */

export default {
  "alpha2": "SA",
  "alpha3": "SAU",
  "country_code": "966",
  "country_name": "Saudi Arabia",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    9
  ]
};