/** generated by scripts/split.js */

export default {
  "alpha2": "YE",
  "alpha3": "YEM",
  "country_code": "967",
  "country_name": "Yemen",
  "mobile_begin_with": [
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};