/** generated by scripts/split.js */

export default {
  "alpha2": "OM",
  "alpha3": "OMN",
  "country_code": "968",
  "country_name": "Oman",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};