/** generated by scripts/split.js */

export default {
  "alpha2": "PS",
  "alpha3": "PSE",
  "country_code": "970",
  "country_name": "Palestinian Territory, Occupied",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    9
  ]
};