/** generated by scripts/split.js */

export default {
  "alpha2": "AE",
  "alpha3": "ARE",
  "country_code": "971",
  "country_name": "United Arab Emirates",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    9
  ]
};