/** generated by scripts/split.js */

export default {
  "alpha2": "IL",
  "alpha3": "ISR",
  "country_code": "972",
  "country_name": "Israel",
  "mobile_begin_with": [
    "5"
  ],
  "phone_number_lengths": [
    9
  ]
};