/** generated by scripts/split.js */

export default {
  "alpha2": "BH",
  "alpha3": "BHR",
  "country_code": "973",
  "country_name": "Bahrain",
  "mobile_begin_with": [
    "3"
  ],
  "phone_number_lengths": [
    8
  ]
};