/** generated by scripts/split.js */

export default {
  "alpha2": "QA",
  "alpha3": "QAT",
  "country_code": "974",
  "country_name": "Qatar",
  "mobile_begin_with": [
    "3",
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    8
  ]
};