/** generated by scripts/split.js */

export default {
  "alpha2": "BT",
  "alpha3": "BTN",
  "country_code": "975",
  "country_name": "Bhutan",
  "mobile_begin_with": [
    "17"
  ],
  "phone_number_lengths": [
    8
  ]
};