/** generated by scripts/split.js */

export default {
  "alpha2": "MN",
  "alpha3": "MNG",
  "country_code": "976",
  "country_name": "Mongolia",
  "mobile_begin_with": [
    "5",
    "8",
    "9"
  ],
  "phone_number_lengths": [
    8
  ]
};