/** generated by scripts/split.js */

export default {
  "alpha2": "NP",
  "alpha3": "NPL",
  "country_code": "977",
  "country_name": "Nepal",
  "mobile_begin_with": [
    "97",
    "98"
  ],
  "phone_number_lengths": [
    10
  ]
};