/** generated by scripts/split.js */

export default {
  "alpha2": "IR",
  "alpha3": "IRN",
  "country_code": "98",
  "country_name": "Iran, Islamic Republic Of",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    10
  ]
};