/** generated by scripts/split.js */

export default {
  "alpha2": "TJ",
  "alpha3": "TJK",
  "country_code": "992",
  "country_name": "Tajikistan",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};