/** generated by scripts/split.js */

export default {
  "alpha2": "TM",
  "alpha3": "TKM",
  "country_code": "993",
  "country_name": "Turkmenistan",
  "mobile_begin_with": [
    "6"
  ],
  "phone_number_lengths": [
    8
  ]
};