/** generated by scripts/split.js */

export default {
  "alpha2": "AZ",
  "alpha3": "AZE",
  "country_code": "994",
  "country_name": "Azerbaijan",
  "mobile_begin_with": [
    "4",
    "5",
    "6",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};