/** generated by scripts/split.js */

export default {
  "alpha2": "GE",
  "alpha3": "GEO",
  "country_code": "995",
  "country_name": "Georgia",
  "mobile_begin_with": [
    "5",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};