/** generated by scripts/split.js */

export default {
  "alpha2": "KG",
  "alpha3": "KGZ",
  "country_code": "996",
  "country_name": "Kyrgyzstan",
  "mobile_begin_with": [
    "5",
    "7"
  ],
  "phone_number_lengths": [
    9
  ]
};