/** generated by scripts/split.js */

export default {
  "alpha2": "UZ",
  "alpha3": "UZB",
  "country_code": "998",
  "country_name": "Uzbekistan",
  "mobile_begin_with": [
    "9"
  ],
  "phone_number_lengths": [
    9
  ]
};