/** generated by scripts/split.js */

/** United States */
import USA from './iso3166Data/1_USA';
/** Aruba */
import ABW from './iso3166Data/297_ABW';
/** Afghanistan */
import AFG from './iso3166Data/93_AFG';
/** Angola */
import AGO from './iso3166Data/244_AGO';
/** Anguilla */
import AIA from './iso3166Data/1_AIA';
/** Åland Islands */
import ALA from './iso3166Data/358_ALA';
/** Albania */
import ALB from './iso3166Data/355_ALB';
/** Andorra */
import AND from './iso3166Data/376_AND';
/** United Arab Emirates */
import ARE from './iso3166Data/971_ARE';
/** Argentina */
import ARG from './iso3166Data/54_ARG';
/** Armenia */
import ARM from './iso3166Data/374_ARM';
/** American Samoa */
import ASM from './iso3166Data/1_ASM';
/** Antigua and Barbuda */
import ATG from './iso3166Data/1_ATG';
/** Australia */
import AUS from './iso3166Data/61_AUS';
/** Austria */
import AUT from './iso3166Data/43_AUT';
/** Azerbaijan */
import AZE from './iso3166Data/994_AZE';
/** Burundi */
import BDI from './iso3166Data/257_BDI';
/** Belgium */
import BEL from './iso3166Data/32_BEL';
/** Benin */
import BEN from './iso3166Data/229_BEN';
/** Burkina Faso */
import BFA from './iso3166Data/226_BFA';
/** Bangladesh */
import BGD from './iso3166Data/880_BGD';
/** Bulgaria */
import BGR from './iso3166Data/359_BGR';
/** Bahrain */
import BHR from './iso3166Data/973_BHR';
/** Bahamas */
import BHS from './iso3166Data/1_BHS';
/** Bosnia and Herzegovina */
import BIH from './iso3166Data/387_BIH';
/** Belarus */
import BLR from './iso3166Data/375_BLR';
/** Belize */
import BLZ from './iso3166Data/501_BLZ';
/** Bermuda */
import BMU from './iso3166Data/1_BMU';
/** Bolivia */
import BOL from './iso3166Data/591_BOL';
/** Brazil */
import BRA from './iso3166Data/55_BRA';
/** Barbados */
import BRB from './iso3166Data/1_BRB';
/** Brunei Darussalam */
import BRN from './iso3166Data/673_BRN';
/** Bhutan */
import BTN from './iso3166Data/975_BTN';
/** Botswana */
import BWA from './iso3166Data/267_BWA';
/** Central African Republic */
import CAF from './iso3166Data/236_CAF';
/** Canada */
import CAN from './iso3166Data/1_CAN';
/** Switzerland */
import CHE from './iso3166Data/41_CHE';
/** Chile */
import CHL from './iso3166Data/56_CHL';
/** China */
import CHN from './iso3166Data/86_CHN';
/** Côte D'Ivoire */
import CIV from './iso3166Data/225_CIV';
/** Cameroon */
import CMR from './iso3166Data/237_CMR';
/** Congo, The Democratic Republic Of The */
import COD from './iso3166Data/243_COD';
/** Congo */
import COG from './iso3166Data/242_COG';
/** Cook Islands */
import COK from './iso3166Data/682_COK';
/** Colombia */
import COL from './iso3166Data/57_COL';
/** Comoros */
import COM from './iso3166Data/269_COM';
/** Cape Verde */
import CPV from './iso3166Data/238_CPV';
/** Costa Rica */
import CRI from './iso3166Data/506_CRI';
/** Cuba */
import CUB from './iso3166Data/53_CUB';
/** Cayman Islands */
import CYM from './iso3166Data/1_CYM';
/** Cyprus */
import CYP from './iso3166Data/357_CYP';
/** Czech Republic */
import CZE from './iso3166Data/420_CZE';
/** Germany */
import DEU from './iso3166Data/49_DEU';
/** Djibouti */
import DJI from './iso3166Data/253_DJI';
/** Dominica */
import DMA from './iso3166Data/1_DMA';
/** Denmark */
import DNK from './iso3166Data/45_DNK';
/** Dominican Republic */
import DOM from './iso3166Data/1_DOM';
/** Algeria */
import DZA from './iso3166Data/213_DZA';
/** Ecuador */
import ECU from './iso3166Data/593_ECU';
/** Egypt */
import EGY from './iso3166Data/20_EGY';
/** Eritrea */
import ERI from './iso3166Data/291_ERI';
/** Spain */
import ESP from './iso3166Data/34_ESP';
/** Estonia */
import EST from './iso3166Data/372_EST';
/** Ethiopia */
import ETH from './iso3166Data/251_ETH';
/** Finland */
import FIN from './iso3166Data/358_FIN';
/** Fiji */
import FJI from './iso3166Data/679_FJI';
/** Falkland Islands (Malvinas) */
import FLK from './iso3166Data/500_FLK';
/** France */
import FRA from './iso3166Data/33_FRA';
/** Faroe Islands */
import FRO from './iso3166Data/298_FRO';
/** Micronesia, Federated States Of */
import FSM from './iso3166Data/691_FSM';
/** Gabon */
import GAB from './iso3166Data/241_GAB';
/** United Kingdom */
import GBR from './iso3166Data/44_GBR';
/** Georgia */
import GEO from './iso3166Data/995_GEO';
/** Ghana */
import GHA from './iso3166Data/233_GHA';
/** Gibraltar */
import GIB from './iso3166Data/350_GIB';
/** Guinea */
import GIN from './iso3166Data/224_GIN';
/** Guadeloupe */
import GLP from './iso3166Data/590_GLP';
/** Gambia */
import GMB from './iso3166Data/220_GMB';
/** Guinea-Bissau */
import GNB from './iso3166Data/245_GNB';
/** Equatorial Guinea */
import GNQ from './iso3166Data/240_GNQ';
/** Greece */
import GRC from './iso3166Data/30_GRC';
/** Grenada */
import GRD from './iso3166Data/1_GRD';
/** Greenland */
import GRL from './iso3166Data/299_GRL';
/** Guatemala */
import GTM from './iso3166Data/502_GTM';
/** French Guiana */
import GUF from './iso3166Data/594_GUF';
/** Guam */
import GUM from './iso3166Data/1_GUM';
/** Guyana */
import GUY from './iso3166Data/592_GUY';
/** Hong Kong */
import HKG from './iso3166Data/852_HKG';
/** Honduras */
import HND from './iso3166Data/504_HND';
/** Croatia */
import HRV from './iso3166Data/385_HRV';
/** Haiti */
import HTI from './iso3166Data/509_HTI';
/** Hungary */
import HUN from './iso3166Data/36_HUN';
/** Indonesia */
import IDN from './iso3166Data/62_IDN';
/** India */
import IND from './iso3166Data/91_IND';
/** Ireland */
import IRL from './iso3166Data/353_IRL';
/** Iran, Islamic Republic Of */
import IRN from './iso3166Data/98_IRN';
/** Iraq */
import IRQ from './iso3166Data/964_IRQ';
/** Iceland */
import ISL from './iso3166Data/354_ISL';
/** Israel */
import ISR from './iso3166Data/972_ISR';
/** Italy */
import ITA from './iso3166Data/39_ITA';
/** Jamaica */
import JAM from './iso3166Data/1_JAM';
/** Jordan */
import JOR from './iso3166Data/962_JOR';
/** Japan */
import JPN from './iso3166Data/81_JPN';
/** Kazakhstan */
import KAZ from './iso3166Data/7_KAZ';
/** Kenya */
import KEN from './iso3166Data/254_KEN';
/** Kyrgyzstan */
import KGZ from './iso3166Data/996_KGZ';
/** Cambodia */
import KHM from './iso3166Data/855_KHM';
/** Kiribati */
import KIR from './iso3166Data/686_KIR';
/** Saint Kitts And Nevis */
import KNA from './iso3166Data/1_KNA';
/** Korea, Republic of */
import KOR from './iso3166Data/82_KOR';
/** Kuwait */
import KWT from './iso3166Data/965_KWT';
/** Lao People's Democratic Republic */
import LAO from './iso3166Data/856_LAO';
/** Lebanon */
import LBN from './iso3166Data/961_LBN';
/** Liberia */
import LBR from './iso3166Data/231_LBR';
/** Libyan Arab Jamahiriya */
import LBY from './iso3166Data/218_LBY';
/** Saint Lucia */
import LCA from './iso3166Data/1_LCA';
/** Liechtenstein */
import LIE from './iso3166Data/423_LIE';
/** Sri Lanka */
import LKA from './iso3166Data/94_LKA';
/** Lesotho */
import LSO from './iso3166Data/266_LSO';
/** Lithuania */
import LTU from './iso3166Data/370_LTU';
/** Luxembourg */
import LUX from './iso3166Data/352_LUX';
/** Latvia */
import LVA from './iso3166Data/371_LVA';
/** Macao */
import MAC from './iso3166Data/853_MAC';
/** Morocco */
import MAR from './iso3166Data/212_MAR';
/** Monaco */
import MCO from './iso3166Data/377_MCO';
/** Moldova, Republic of */
import MDA from './iso3166Data/373_MDA';
/** Madagascar */
import MDG from './iso3166Data/261_MDG';
/** Maldives */
import MDV from './iso3166Data/960_MDV';
/** Mexico */
import MEX from './iso3166Data/52_MEX';
/** Marshall Islands */
import MHL from './iso3166Data/692_MHL';
/** Macedonia, the Former Yugoslav Republic Of */
import MKD from './iso3166Data/389_MKD';
/** Mali */
import MLI from './iso3166Data/223_MLI';
/** Malta */
import MLT from './iso3166Data/356_MLT';
/** Myanmar */
import MMR from './iso3166Data/95_MMR';
/** Montenegro */
import MNE from './iso3166Data/382_MNE';
/** Mongolia */
import MNG from './iso3166Data/976_MNG';
/** Northern Mariana Islands */
import MNP from './iso3166Data/1_MNP';
/** Mozambique */
import MOZ from './iso3166Data/258_MOZ';
/** Mauritania */
import MRT from './iso3166Data/222_MRT';
/** Montserrat */
import MSR from './iso3166Data/1_MSR';
/** Martinique */
import MTQ from './iso3166Data/596_MTQ';
/** Mauritius */
import MUS from './iso3166Data/230_MUS';
/** Malawi */
import MWI from './iso3166Data/265_MWI';
/** Malaysia */
import MYS from './iso3166Data/60_MYS';
/** Mayotte */
import MYT from './iso3166Data/262_MYT';
/** Namibia */
import NAM from './iso3166Data/264_NAM';
/** New Caledonia */
import NCL from './iso3166Data/687_NCL';
/** Niger */
import NER from './iso3166Data/227_NER';
/** Norfolk Island */
import NFK from './iso3166Data/672_NFK';
/** Nigeria */
import NGA from './iso3166Data/234_NGA';
/** Nicaragua */
import NIC from './iso3166Data/505_NIC';
/** Niue */
import NIU from './iso3166Data/683_NIU';
/** Netherlands */
import NLD from './iso3166Data/31_NLD';
/** Norway */
import NOR from './iso3166Data/47_NOR';
/** Nepal */
import NPL from './iso3166Data/977_NPL';
/** Nauru */
import NRU from './iso3166Data/674_NRU';
/** New Zealand */
import NZL from './iso3166Data/64_NZL';
/** Oman */
import OMN from './iso3166Data/968_OMN';
/** Pakistan */
import PAK from './iso3166Data/92_PAK';
/** Panama */
import PAN from './iso3166Data/507_PAN';
/** Peru */
import PER from './iso3166Data/51_PER';
/** Philippines */
import PHL from './iso3166Data/63_PHL';
/** Palau */
import PLW from './iso3166Data/680_PLW';
/** Papua New Guinea */
import PNG from './iso3166Data/675_PNG';
/** Poland */
import POL from './iso3166Data/48_POL';
/** Puerto Rico */
import PRI from './iso3166Data/1_PRI';
/** Portugal */
import PRT from './iso3166Data/351_PRT';
/** Paraguay */
import PRY from './iso3166Data/595_PRY';
/** Palestinian Territory, Occupied */
import PSE from './iso3166Data/970_PSE';
/** French Polynesia */
import PYF from './iso3166Data/689_PYF';
/** Qatar */
import QAT from './iso3166Data/974_QAT';
/** Réunion */
import REU from './iso3166Data/262_REU';
/** Romania */
import ROU from './iso3166Data/40_ROU';
/** Russian Federation */
import RUS from './iso3166Data/7_RUS';
/** Rwanda */
import RWA from './iso3166Data/250_RWA';
/** Saudi Arabia */
import SAU from './iso3166Data/966_SAU';
/** Sudan */
import SDN from './iso3166Data/249_SDN';
/** South Sudan */
import SSD from './iso3166Data/211_SSD';
/** Senegal */
import SEN from './iso3166Data/221_SEN';
/** Singapore */
import SGP from './iso3166Data/65_SGP';
/** Saint Helena */
import SHN from './iso3166Data/290_SHN';
/** Svalbard And Jan Mayen */
import SJM from './iso3166Data/47_SJM';
/** Solomon Islands */
import SLB from './iso3166Data/677_SLB';
/** Sierra Leone */
import SLE from './iso3166Data/232_SLE';
/** El Salvador */
import SLV from './iso3166Data/503_SLV';
/** San Marino */
import SMR from './iso3166Data/378_SMR';
/** Somalia */
import SOM from './iso3166Data/252_SOM';
/** Sint Maarten */
import SXM from './iso3166Data/1_SXM';
/** Saint Pierre And Miquelon */
import SPM from './iso3166Data/508_SPM';
/** Serbia */
import SRB from './iso3166Data/381_SRB';
/** Sao Tome and Principe */
import STP from './iso3166Data/239_STP';
/** Suriname */
import SUR from './iso3166Data/597_SUR';
/** Slovakia */
import SVK from './iso3166Data/421_SVK';
/** Slovenia */
import SVN from './iso3166Data/386_SVN';
/** Sweden */
import SWE from './iso3166Data/46_SWE';
/** Seychelles */
import SYC from './iso3166Data/248_SYC';
/** Syrian Arab Republic */
import SYR from './iso3166Data/963_SYR';
/** Turks and Caicos Islands */
import TCA from './iso3166Data/1_TCA';
/** Chad */
import TCD from './iso3166Data/235_TCD';
/** Togo */
import TGO from './iso3166Data/228_TGO';
/** Thailand */
import THA from './iso3166Data/66_THA';
/** Tajikistan */
import TJK from './iso3166Data/992_TJK';
/** Tokelau */
import TKL from './iso3166Data/690_TKL';
/** Turkmenistan */
import TKM from './iso3166Data/993_TKM';
/** Timor-Leste */
import TLS from './iso3166Data/670_TLS';
/** Tonga */
import TON from './iso3166Data/676_TON';
/** Trinidad and Tobago */
import TTO from './iso3166Data/1_TTO';
/** Tunisia */
import TUN from './iso3166Data/216_TUN';
/** Turkey */
import TUR from './iso3166Data/90_TUR';
/** Tuvalu */
import TUV from './iso3166Data/688_TUV';
/** Taiwan */
import TWN from './iso3166Data/886_TWN';
/** Tanzania, United Republic of */
import TZA from './iso3166Data/255_TZA';
/** Uganda */
import UGA from './iso3166Data/256_UGA';
/** Ukraine */
import UKR from './iso3166Data/380_UKR';
/** Uruguay */
import URY from './iso3166Data/598_URY';
/** Uzbekistan */
import UZB from './iso3166Data/998_UZB';
/** Saint Vincent And The Grenedines */
import VCT from './iso3166Data/1_VCT';
/** Venezuela, Bolivarian Republic of */
import VEN from './iso3166Data/58_VEN';
/** Virgin Islands, British */
import VGB from './iso3166Data/1_VGB';
/** Virgin Islands, U.S. */
import VIR from './iso3166Data/1_VIR';
/** Viet Nam */
import VNM from './iso3166Data/84_VNM';
/** Vanuatu */
import VUT from './iso3166Data/678_VUT';
/** Wallis and Futuna */
import WLF from './iso3166Data/681_WLF';
/** Samoa */
import WSM from './iso3166Data/685_WSM';
/** Yemen */
import YEM from './iso3166Data/967_YEM';
/** South Africa */
import ZAF from './iso3166Data/27_ZAF';
/** Zambia */
import ZMB from './iso3166Data/260_ZMB';
/** Zimbabwe */
import ZWE from './iso3166Data/263_ZWE';
import { PhoneType } from './iso3166DataUtils';

export const allData: PhoneType[] = [
  USA,
  ABW,
  AFG,
  AGO,
  AIA,
  ALA,
  ALB,
  AND,
  ARE,
  ARG,
  ARM,
  ASM,
  ATG,
  AUS,
  AUT,
  AZE,
  BDI,
  BEL,
  BEN,
  BFA,
  BGD,
  BGR,
  BHR,
  BHS,
  BIH,
  BLR,
  BLZ,
  BMU,
  BOL,
  BRA,
  BRB,
  BRN,
  BTN,
  BWA,
  CAF,
  CAN,
  CHE,
  CHL,
  CHN,
  CIV,
  CMR,
  COD,
  COG,
  COK,
  COL,
  COM,
  CPV,
  CRI,
  CUB,
  CYM,
  CYP,
  CZE,
  DEU,
  DJI,
  DMA,
  DNK,
  DOM,
  DZA,
  ECU,
  EGY,
  ERI,
  ESP,
  EST,
  ETH,
  FIN,
  FJI,
  FLK,
  FRA,
  FRO,
  FSM,
  GAB,
  GBR,
  GEO,
  GHA,
  GIB,
  GIN,
  GLP,
  GMB,
  GNB,
  GNQ,
  GRC,
  GRD,
  GRL,
  GTM,
  GUF,
  GUM,
  GUY,
  HKG,
  HND,
  HRV,
  HTI,
  HUN,
  IDN,
  IND,
  IRL,
  IRN,
  IRQ,
  ISL,
  ISR,
  ITA,
  JAM,
  JOR,
  JPN,
  KAZ,
  KEN,
  KGZ,
  KHM,
  KIR,
  KNA,
  KOR,
  KWT,
  LAO,
  LBN,
  LBR,
  LBY,
  LCA,
  LIE,
  LKA,
  LSO,
  LTU,
  LUX,
  LVA,
  MAC,
  MAR,
  MCO,
  MDA,
  MDG,
  MDV,
  MEX,
  MHL,
  MKD,
  MLI,
  MLT,
  MMR,
  MNE,
  MNG,
  MNP,
  MOZ,
  MRT,
  MSR,
  MTQ,
  MUS,
  MWI,
  MYS,
  MYT,
  NAM,
  NCL,
  NER,
  NFK,
  NGA,
  NIC,
  NIU,
  NLD,
  NOR,
  NPL,
  NRU,
  NZL,
  OMN,
  PAK,
  PAN,
  PER,
  PHL,
  PLW,
  PNG,
  POL,
  PRI,
  PRT,
  PRY,
  PSE,
  PYF,
  QAT,
  REU,
  ROU,
  RUS,
  RWA,
  SAU,
  SDN,
  SSD,
  SEN,
  SGP,
  SHN,
  SJM,
  SLB,
  SLE,
  SLV,
  SMR,
  SOM,
  SXM,
  SPM,
  SRB,
  STP,
  SUR,
  SVK,
  SVN,
  SWE,
  SYC,
  SYR,
  TCA,
  TCD,
  TGO,
  THA,
  TJK,
  TKL,
  TKM,
  TLS,
  TON,
  TTO,
  TUN,
  TUR,
  TUV,
  TWN,
  TZA,
  UGA,
  UKR,
  URY,
  UZB,
  VCT,
  VEN,
  VGB,
  VIR,
  VNM,
  VUT,
  WLF,
  WSM,
  YEM,
  ZAF,
  ZMB,
  ZWE
];